name: "Litmus Suite Run"
description: "This is workflow for litmus suite run"
author: Manas Verma
branding:
  icon: "activity"
  color: "blue"

inputs:
  suite-id:
    description: "ID of the suite to run"
    required: true
  api-key:
    description: "API key for authentication"
    required: true
  api-url:
    description: "Base URL for the Litmus API"
    required: false
    default: "https://api.litmuscheck.com/api/v1/suite"
  config:
    description: "Configuration object for the suite run (JSON string)"
    required: false
  environment-id:
    description: "Environment ID for the suite run"
    required: false
  tag-filter-condition:
    description: "Tag filter condition: 'contains_any' or 'does_not_contain_any'"
    required: false
  tag-list:
    description: "List of tags (JSON array string or comma-separated list)"
    required: false
  emails:
    description: "Email addresses to override suite config emails (JSON array string or comma-separated list)"
    required: false

outputs:
  suite-result:
    description: "Final suite run result as JSON"
    value: ${{ steps.litmus.outputs.suite-result }}

runs:
  using: docker
  image: Dockerfile
  env:
    LITMUS_API_KEY: ${{ inputs.api-key }}
    LITMUS_API_URL: ${{ inputs.api-url }}
    LITMUS_CONFIG: ${{ inputs.config }}
    LITMUS_ENVIRONMENT_ID: ${{ inputs.environment-id }}
    LITMUS_TAG_FILTER_CONDITION: ${{ inputs.tag-filter-condition }}
    LITMUS_TAG_LIST: ${{ inputs.tag-list }}
    LITMUS_EMAILS: ${{ inputs.emails }}
  args:
    - ${{ inputs.suite-id }}
