name: "Hello World"
description: "This is a simple hello world action"
author: Manas Verma
branding:
  icon: "activity"
  color: "blue"

inputs:
  custom-text:
    description: "Hellooooo world!!!!"
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.custom-text }}
  architecture: linux/amd64