name: "Litmus Suite Run"
description: "This is workflow for litmus suite run"
author: Manas Verma
branding:
  icon: "activity"
  color: "blue"

inputs:
  custom-text:
    description: "Custom text for the litmus suite run"
    required: true
  api-key:
    description: "API key for authentication"
    required: true

runs:
  using: docker
  image: Dockerfile
  env:
    API_KEY: ${{ inputs.api-key }}
  args:
    - ${{ inputs.custom-text }}