name: 'litmus_run'
description: 'Run litmus suite run API'
# branding:
#   icon: 'play'
#   color: 'blue'
inputs:
  name:
    description: 'Manas Verma'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Run Python script
      shell: bash
      run: python GitHubActionsFormatter.py