name: "Litmus Suite Run"
description: "This is workflow for litmus suite run"
author: Manas Verma
branding:
  icon: "activity"
  color: "blue"

inputs:
  suite-id:
    description: "ID of the suite to run"
    required: true
  api-url:
    description: "Base URL for the Litmus API"
    required: false
    default: "https://qualiumdev.finigami.com/api/v1/suite"

runs:
  using: docker
  image: Dockerfile
  env:
    LITMUS_API_URL: ${{ inputs.api-url }}
  args:
    - ${{ inputs.suite-id }}