name: "Litmus Suite Run"
description: "This is workflow for litmus suite run"
author: Manas Verma
branding:
  icon: "activity"
  color: "blue"

inputs:
  suite-id:
    description: "ID of the suite to run"
    required: true
  api-key:
    description: "API key for authentication"
    required: true
  api-url:
    description: "Base URL for the Litmus API"
    required: false
    default: "https://api.litmuscheck.com/api/v1/suite"
  config:
    description: "Configuration object for the suite run (JSON string)"
    required: false
  environment-id:
    description: "Environment ID for the suite run"
    required: false
  environment-name:
    description: "Environment by name - only one of id or name should be passed"
    required: false
  environment-variables:
    description: "Additional variables to be used in the environment"
    required: false

outputs:
  suite-result:
    description: "Final suite run result as JSON"
    value: ${{ steps.litmus.outputs.suite-result }}

runs:
  using: docker
  image: Dockerfile
  env:
    LITMUS_API_KEY: ${{ inputs.api-key }}
    LITMUS_API_URL: ${{ inputs.api-url }}
    LITMUS_CONFIG: ${{ inputs.config }}
    LITMUS_ENVIRONMENT_ID: ${{ inputs.environment-id }}
    LITMUS_ENVIRONMENT_NAME: ${{ inputs.environment-name }}
    LITMUS_ENVIRONMENT_VARIABLES: ${{ inputs.environment-variables }}
  args:
    - ${{ inputs.suite-id }}

