name: Trigger suite run qualium-ai API

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Run suite run API
        run: |
          curl -X POST 'https://qualiumdev.finigami.com/api/v1/suite/9732bec7-387a-4844-bfc1-52a9a61b1382/run' \
            --header 'api-key: $secrets.API_KEY'

      - name: Poll suite status data every 10 sec
        run: |
            RESPONSE=$(curl GET 'https://qualiumdev.finigami.com/api/v1/suite/9732bec7-387a-4844-bfc1-52a9a61b1382/runs' \
            --header 'api-key: $secrets.API_KEY')
            echo "Response from API:"
            echo "$RESPONSE"      